version: '3.9'
services:
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    container_name: backend
    environment:
      POSTGRES_PASSWORD: fastify
      POSTGRES_USER: fastify
      POSTGRES_DB: fastify
    ports:
    - 5434:5432
    volumes:
    - ./pgdata:/var/lib/postgresql/data
